
CREATE TABLE AGARE (
 PERSONNRID        INT(13) NOT NULL,
 PID            VARCHAR(5) NOT NULL);


CREATE TABLE ANSTALLD (
 PERSONNRID          INT(13) NOT NULL,
 ANSTALLNINGSID      INT(2) NOT NULL);

CREATE TABLE PERSONFORETAG (
 PERSONNRID        INT(13) NOT NULL,
 STAT     		VARCHAR(15),
 STAD          	VARCHAR(20),
 GATUNR   		VARCHAR(100),
 EFTERNAMNF     VARCHAR(70),
 FORNAMN     	VARCHAR(30),
 TELEFON        VARCHAR(20));



CREATE TABLE BRICKAMODELL (
 SERIENUMMER         VARCHAR(16) NOT NULL,
 PID                 VARCHAR(5) NOT NULL, 
 MODELL              VARCHAR(30) NOT NULL,
 PLATS               VARCHAR(50),
 DATUMTID       	 DATETIME); /*BRICKANS KLOCKADE TID */

CREATE TABLE KALENDER (
DATUM       	 DATETIME NOT NULL); /*DATABASENS MOTAGNA TID */



CREATE TABLE MODELL (
 MODELL              VARCHAR(30) NOT NULL);

CREATE TABLE BRICKALOG (
 SERIENUMMER         VARCHAR(16) NOT NULL,
 PID                 VARCHAR(5) NOT NULL, 
 DATUM       	 	 DATETIME NOT NULL, /*DATABASENS MOTAGNA TID */
 MODELL              VARCHAR(30) NOT NULL);

