
ALTER TABLE AGARE ADD CONSTRAINT AGARE_PK PRIMARY KEY (PID);

ALTER TABLE ANSTALLD ADD CONSTRAINT ANSTALLD_PK PRIMARY KEY (ANSTALLNINGSID);

ALTER TABLE PERSONFORETAG ADD CONSTRAINT PERSONFORETAG_PK PRIMARY KEY (PERSONNRID);

ALTER TABLE BRICKAMODELL ADD CONSTRAINT BRICKAMODELL_PK PRIMARY KEY (SERIENUMMER);

ALTER TABLE MODELL ADD CONSTRAINT MODELL_PK PRIMARY KEY (MODELL);

ALTER TABLE KALENDER ADD CONSTRAINT KALENDER_PK PRIMARY KEY (DATUM);

ALTER TABLE BRICKALOG ADD CONSTRAINT BRICKALOG_PK PRIMARY KEY (SERIENUMMER, PID, MODELL, DATUM);



ALTER TABLE AGARE ADD CONSTRAINT AGARE_FK FOREIGN KEY (PERSONNRID) REFERENCES PERSONFORETAG(PERSONNRID);


ALTER TABLE ANSTALLD ADD CONSTRAINT ANSTALLD_FK FOREIGN KEY (PERSONNRID) REFERENCES PERSONFORETAG(PERSONNRID);


ALTER TABLE STAD ADD CONSTRAINT STAD_FK FOREIGN KEY (STAT) REFERENCES STAT(STAT);


ALTER TABLE ADRESS ADD CONSTRAINT ADRESS_FK FOREIGN KEY (STAT) REFERENCES STAD(STAT);

ALTER TABLE ADRESS ADD CONSTRAINT ADRESS2_FK FOREIGN KEY (STAD) REFERENCES STAD(STAD);


ALTER TABLE PERSONFORETAG ADD CONSTRAINT PERSONFORETAG_FK FOREIGN KEY (STAT) REFERENCES ADRESS(STAT);

ALTER TABLE PERSONFORETAG ADD CONSTRAINT PERSONFORETAG2_FK FOREIGN KEY (STAD) REFERENCES ADRESS(STAD);

ALTER TABLE PERSONFORETAG ADD CONSTRAINT PERSONFORETAG3_FK FOREIGN KEY (GATUNR) REFERENCES ADRESS(GATUNR);


ALTER TABLE RAS ADD CONSTRAINT RAS_FK FOREIGN KEY (ART) REFERENCES ART(ART);


ALTER TABLE DJUR ADD CONSTRAINT DJUR_FK FOREIGN KEY (RAS) REFERENCES RAS(RAS);

ALTER TABLE DJUR ADD CONSTRAINT DJUR2_FK FOREIGN KEY (ART) REFERENCES RAS(ART);

ALTER TABLE DJUR ADD CONSTRAINT DJUR3_FK FOREIGN KEY (AGARID) REFERENCES AGARE(AGARID);




ALTER TABLE BESOK ADD CONSTRAINT BESOK_FK FOREIGN KEY (ANSTALLNINGSID) REFERENCES ANSTALLD(ANSTALLNINGSID);

ALTER TABLE BESOK ADD CONSTRAINT BESOK2_FK FOREIGN KEY (AGARID) REFERENCES DJUR(AGARID);

ALTER TABLE BESOK ADD CONSTRAINT BESOK3_FK FOREIGN KEY (DJURID) REFERENCES DJUR(DJURID);




ALTER TABLE UTFORDATJANSTER ADD CONSTRAINT UTFORDATJANSTER_FK FOREIGN KEY (KOD) REFERENCES BESOK(KOD);

ALTER TABLE UTFORDATJANSTER ADD CONSTRAINT UTFORDATJANSTER2_FK FOREIGN KEY (TJANSTID) REFERENCES TJANST(TJANSTID);
